### PR TITLE
Changed imaqal layout to be the same as worldbank's

### PR DESCRIPTION
**Pull request by DanielMwendwa**

### CODE REVIEW

**Review by IsaackMwenda — CHANGES_REQUESTED** [review]
Hi @DanielMwendwa please add a screenshot for quick review.

**Comment by DanielMwendwa** [comment]
imaqal

**Comment by DanielMwendwa** [comment]
https://github.com/AfricasVoices/Operations-Dashboard/pull/89/commits/769240e0d29b5b12f2708f562e60ee8aa2fcbb82 Closes: #91
x-axis

**Comment by DanielMwendwa** [comment]
@IsaackMwenda every issue concerning Imaqal  has been resolved.

**Comment by IsaackMwenda** [comment]
> @IsaackMwenda every issue concerning Imaqal has been resolved.

@DanielMwendwa please fix the merge conflicts and ping me to re-review.

**Comment by DanielMwendwa** [comment]
@IsaackMwenda  I have resolved the main issue with this branch concerning the failed messages graph where by the line graph was extending beyond the width of the x-axis.

**Comment by DanielMwendwa** [comment]
@IsaackMwenda I'll create another branch for Imaqal where I'll just make changes that have been approved on worldbank. I think that way it we would be able to finish on all the critical changes before deployment. #106

**Pull request closed without merging**
