### PR TITLE
Issue 38 log scale

### PR DESCRIPTION
**Pull request by ritazagoni**

### CODE REVIEW

**Comment by lukechurch** [comment]
Hi @ritazagoni 

I don't quite follow the intention here. Is the submission of the _log version intended to be an experiment of 'the system with the ability to do log plotting' - with the intention that we would replace the existing file with it, or is the intention that we keep both files and switch between the chart forms by switching HTML file?

If the later - I'm a bit concerned about the code duplication, we already have way too much code duplication from the way in which these charts are built, rather than using templating, I'm a bit scared of adding any combinatorial expansion to that...

**Comment by ritazagoni** [comment]
Sorry not being clear - the intention is to have one HTML file + js that do the switching, I just didn't want to break the existing setup, as I'm also thinking we should integrate the stacked bar view in switching and have a dropdown for log and stack (and linear if that still makes sense to keep, I'm not sure)

**Comment by lukechurch** [comment]
Thanks @ritazagoni as discussed LGTM to merge and iterate

**Review by lukechurch — APPROVED** [review]

**Comment by lukechurch** [comment]
@ritazagoni Shall we close this?

**Comment by ritazagoni** [comment]
Agree, let's close it as y-axis capping is implemented.

**Comment by lukechurch** [comment]
Thanks @ritazagoni

**Pull request closed without merging**
