### PR TITLE
revert changes made on master branch

### LINKED ISSUE #157: Day View Broken on Master
The day bars are currently misaligned and drawing on top of each other on master:
image

This bug appears to have been introduced by 0e25b092e681c18ecfb54f865ffff18da6d0806c.

### PR DESCRIPTION
**Pull request by DanielMwendwa**
Closes: #157

### CODE REVIEW

**Comment by as2388** [comment]
Re-opens #145

**Review by as2388 — CHANGES_REQUESTED** [review]
Could you add a note to the PR description saying what you are reverting? Ideally by including the hash of the commit that is being reverted by the pull request (which I thought `$ git revert` did by default?), and by including a reference to the PR that originally introduced the change.

Otherwise it's difficult to check the revert.

**Comment by as2388** [comment]
Also, this is a pretty extreme workaround for what I don't imagine is a particularly complex fix. It may be worth spending an hour or so trying to fix before reverting.

**Comment by DanielMwendwa** [comment]
Thanks @as2388 please take a look at #162

**Pull request closed without merging**
